# Generated by Django 2.2.13 on 2020-06-29 12:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='headline')),
                ('cover', models.ImageField(upload_to='static/images/banner', verbose_name='rolling picture')),
                ('link_url', models.URLField(max_length=100, verbose_name='image links')),
                ('idx', models.IntegerField(verbose_name='index')),
                ('is_active', models.BooleanField(default=False, verbose_name='whether to set to active')),
            ],
            options={
                'verbose_name': 'rolling picture',
                'verbose_name_plural': 'rolling picture',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='category name')),
            ],
            options={
                'verbose_name': 'blog classification',
                'verbose_name_plural': 'blog classification',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='release date')),
                ('content', models.TextField(verbose_name='content')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comment',
            },
        ),
        migrations.CreateModel(
            name='FriendlyLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='headline')),
                ('link', models.URLField(default='', max_length=50, verbose_name='link')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'link',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='label name')),
            ],
            options={
                'verbose_name': 'label',
                'verbose_name_plural': 'label',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='headline')),
                ('content', models.TextField(verbose_name='content')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='release date')),
                ('cover', models.ImageField(default=None, upload_to='static/images/post', verbose_name='blog covers')),
                ('views', models.IntegerField(default=0, verbose_name='page view')),
                ('recommend', models.BooleanField(default=False, verbose_name='recommend the blog')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogs.BlogCategory', verbose_name='blog classification')),
                ('tags', models.ManyToManyField(to='blogs.Tags', verbose_name='label')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blog',
            },
        ),
    ]
